version: '3.3'

services:
  flourio_app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app:cached
      - /app/node_modules

  postgres_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: mebee
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: sample
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
