FROM node:16
WORKDIR /app_server

# install packages
# RUN apt update && \
# 	apt install -y nodejs && \
# 	rm -rf /var/lib/apt/lists/*

# install dependencies (server side)
COPY ./package.json ./
RUN npm install

# copy source code
COPY . .

# exec application
CMD ["node", "index.js"]
 