version: '3.3'

services:
  frourio_dev:
    build:
      context: ../
      dockerfile: ./.devcontainer/dockerfile
    user: node
    ports:
      - "8000:8000"
    volumes:
      - ..:/app:cached
      - ../server/node_modules:/app/server/node_modules:cached
      - ../node_modules:/app/node_modules:cached
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

    

volumes:
  postgres:
