version: '3.3'

services:
  frourio_dev:
    build:
      context: ../
      dockerfile: ./.devcontainer/dockerfile
    user: node
    ports:
      - "8000:8000"
    volumes:
      - ..:/app:cached
      - ../server/node_modules:/app/server/node_modules:cached
      - ../node_modules:/app/node_modules:cached

  # postgres_db:
  #   image: postgres:11
  #   restart: always
  #   environment:
  #     POSTGRES_USER: mebee
  #     POSTGRES_PASSWORD: password
  #     PGPASSWORD: password123
  #     POSTGRES_DB: sample
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

volumes:
  postgres:
